//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Award
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int TrophyId { get; set; }
        public string Reason { get; set; }
        public System.DateTime AwardedOn { get; set; }
        public Nullable<int> NominatedById { get; set; }
        public Nullable<System.DateTime> NominatedDate { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Player NominatedBy { get; set; }
        public virtual Trophy Trophy { get; set; }
    }
}
