//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public Page()
        {
            this.Related = new HashSet<Page>();
            this.Related1 = new HashSet<Page>();
            this.PageViews = new HashSet<PageView>();
        }
    
        public int Id { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Description { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMime { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public int CreatedById { get; set; }
        public int ModifedById { get; set; }
        public int SignificantUpdateById { get; set; }
        public System.DateTime SignificantUpdate { get; set; }
        public bool Pinned { get; set; }
    
        public virtual ICollection<Page> Related { get; set; }
        internal virtual ICollection<Page> Related1 { get; set; }
        public virtual Player CreatedBy { get; set; }
        public virtual Player ModifiedBy { get; set; }
        public virtual ICollection<PageView> PageViews { get; set; }
    }
}
