//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.SessionLogs = new HashSet<SessionLog>();
            this.Sessions = new HashSet<Session>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public System.DateTime Modified { get; set; }
        public System.DateTime Created { get; set; }
        public int ModifiedByPlayerId { get; set; }
        public int CreatedByPlayerId { get; set; }
        public int PlayerId { get; set; }
        public int PersonTypeId { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player ModifiedBy { get; set; }
        public virtual Player itedBy { get; set; }
        public virtual ICollection<SessionLog> SessionLogs { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
