//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Pages = new HashSet<Page>();
            this.People = new HashSet<Person>();
            this.Pages1 = new HashSet<Page>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string DisplayName { get; set; }
        public byte[] ImageData { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Page> Pages { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Page> Pages1 { get; set; }
    }
}
