//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.People = new HashSet<Person>();
            this.People1 = new HashSet<Person>();
            this.People2 = new HashSet<Person>();
            this.SessionLogs = new HashSet<SessionLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Person> People1 { get; set; }
        public virtual ICollection<Person> People2 { get; set; }
        public virtual ICollection<SessionLog> SessionLogs { get; set; }
    }
}
